import type { GalleryItem } from "./types";

/**
 * Field notes — the human layer. Secondary to the work, deliberately.
 * To add: drop a compressed image in /public/gallery and add an entry here.
 */
export const gallery: GalleryItem[] = [
  {
    src: "/gallery/indaba2026_1.jpeg",
    alt: "Presenting the AI agents workshop at Ghana Data Science Summit 2026",
    caption:
      "Presenting “Building Useful AI Agents with Agno + OpenRouter” at the Ghana Data Science Summit / IndabaX Ghana.",
    year: "2026",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/indaba2026_2.jpeg",
    alt: "Workshop session at Ghana Data Science Summit 2026",
    caption: "Working through agent tool use and orchestration with the room.",
    year: "2026",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/indaba2026_3.jpeg",
    alt: "Workshop session at Ghana Data Science Summit 2026",
    caption: "Ghana Data Science Summit / IndabaX Ghana, 2026.",
    year: "2026",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/noeud1.jpeg",
    alt: "Late-night work on Noeud infrastructure",
    caption: "Building Noeud infrastructure. Burning the midnight candle 🕯️",
    year: "2026",
    group: "Building",
  },
  {
    src: "/gallery/noeud2.jpeg",
    alt: "Late-night work on Noeud",
    caption: "Late nights. Rest at the end, not in the middle.",
    year: "2026",
    group: "Building",
  },
  { src: "/gallery/enbw3.jpeg", alt: "Remote work setup", caption: "Remote work at EnBW.", year: "2026", group: "Building" },
  { src: "/gallery/enbw5.jpeg", alt: "Remote work setup", caption: "Remote work at EnBW.", year: "2026", group: "Building" },
  { src: "/gallery/enbw1.jpeg", alt: "Remote work setup", caption: "Remote work at EnBW.", year: "2026", group: "Building" },
  { src: "/gallery/enbw2.jpeg", alt: "Remote work setup", caption: "Remote work at EnBW.", year: "2026", group: "Building" },
  { src: "/gallery/enbw4.jpeg", alt: "Remote work setup", caption: "Remote work at EnBW.", year: "2026", group: "Building" },
  {
    src: "/gallery/3.jpg",
    alt: "Presenting at Tech & Beyond Expo",
    caption: "Presenting on Software Engineering in the Age of AI at Academic City University.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/2.jpg",
    alt: "Speaking at Tech & Beyond Expo 2025",
    caption: "Presenting on Software Engineering in the Age of AI at Academic City University.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/ind1.jpg",
    alt: "LoRA fine-tuning workshop at IndabaX Ghana",
    caption: "LoRA fine-tuning workshop at IndabaX Ghana, Ashesi University.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/ind2.jpg",
    alt: "LoRA fine-tuning workshop at IndabaX Ghana",
    caption: "LoRA fine-tuning workshop at IndabaX Ghana, Ashesi University.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/ind3.jpg",
    alt: "LoRA fine-tuning workshop at IndabaX Ghana",
    caption: "LoRA fine-tuning workshop at IndabaX Ghana, Ashesi University.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/ds3.jpeg",
    alt: "DS-I Africa Consortium Meeting",
    caption: "At the DS-I Africa Consortium Meeting 2025.",
    year: "2025",
    group: "Community",
  },
  {
    src: "/gallery/ds1.jpg",
    alt: "DS-I Africa Consortium Meeting",
    caption: "At the DS-I Africa Consortium Meeting 2025.",
    year: "2025",
    group: "Community",
  },
  {
    src: "/gallery/ds4.jpeg",
    alt: "DS-I Africa Consortium Meeting",
    caption: "At the DS-I Africa Consortium Meeting 2025.",
    year: "2025",
    group: "Community",
  },
  {
    src: "/gallery/cadi1.jpg",
    alt: "First drone mapping site in the Bono Region",
    caption: "First drone mapping site in the Bono Region for the CADI AI pilot.",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/cadi4.jpg",
    alt: "Operating a DJI Phantom 4 Pro with the team",
    caption: "Operating the DJI Phantom 4 Pro with the team, a farmer and an extension officer.",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/cadi9.jpg",
    alt: "Team and a local farmer during field operations",
    caption: "With teammates Donald and BoBT and a local farmer during field operations.",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/cadi2.jpg",
    alt: "Team and extension officer on site",
    caption: "With teammates Donald and BoBT and a local extension officer during field operations.",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/cadi6.jpeg",
    alt: "On the field with the drone bag",
    caption: "On the field with the drone bag — the metal fences here protect yams from hungry cattle 😅",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/cadi3.jpg",
    alt: "Arrival in the Savannah Region",
    caption: "First landing in the Savannah Region with the team for agricultural data collection.",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/cadi5.jpg",
    alt: "Aerial city view from a plane window",
    caption: "Flying back from Sunyani after CADI AI field operations.",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/cadi7.jpeg",
    alt: "At the airport with the team",
    caption: "At the airport with the team after a successful drone mapping mission.",
    year: "2025",
    group: "Field work",
  },
  {
    src: "/gallery/run1.jpeg",
    alt: "Runmila AI Institute Summer Camp",
    caption:
      "Teaching Python and generative AI to students from Montserrat, Grenada and Dominica at the Runmila AI Summer Camp.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/run2.jpeg",
    alt: "Hands-on LLM session at Runmila AI Institute",
    caption: "A hands-on session on large language models and AI agents via Google Colab.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/glb4.jpeg",
    alt: "Mentoring at the Global Code bootcamp",
    caption: "Mentoring students in Python and AI integration at the University of Cape Coast.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/glb3.jpg",
    alt: "Debugging student code at the Global Code bootcamp",
    caption: "Debugging student code with co-instructor Zenas, University of Cape Coast.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/glb5.jpeg",
    alt: "Mentoring at the Global Code bootcamp",
    caption: "Mentoring students in Python and AI integration at the University of Cape Coast.",
    year: "2025",
    group: "Talks & teaching",
  },
  {
    src: "/gallery/glb2.jpg",
    alt: "Presenting ActiveTrack at the Global Code project display",
    caption:
      "Presenting ActiveTrack at the Global Code project display — an AI-driven fitness tracker using IoT, LSTM models and open-source LLMs.",
    year: "2024",
    group: "Earlier",
  },
  {
    src: "/gallery/glb1.jpg",
    alt: "Global Code certificate ceremony",
    caption: "Receiving the certificate for the Global Code 3-week programming camp (Raspberry Pi & Python).",
    year: "2024",
    group: "Earlier",
  },
  {
    src: "/gallery/rob3.jpeg",
    alt: "Robotics and IoT TransforME exhibition",
    caption: "Showcasing the award-winning project at the Robotics and IoT TransforME exhibition.",
    year: "2023",
    group: "Earlier",
  },
  {
    src: "/gallery/rob1.jpg",
    alt: "Best Participant award for robotics and IoT",
    caption: "Best Participant award for performance and innovation in Robotics and IoT.",
    year: "2023",
    group: "Earlier",
  },
  {
    src: "/gallery/rob4.jpeg",
    alt: "Robotics and IoT TransforME exhibition",
    caption: "Showcasing the award-winning project at the Robotics and IoT TransforME exhibition.",
    year: "2023",
    group: "Earlier",
  },
];

export const galleryGroups = [
  "All",
  "Talks & teaching",
  "Field work",
  "Building",
  "Community",
  "Earlier",
];
